- cli/src/commands/publish.rs
Trims the seed to remove spaces and newlines around it.
Fixes #6.
> fix: trim seed when reading

- Cargo.lock
- cli/Cargo.toml
- server/Cargo.toml
Version bumps anydns which comes with a bug fix to resolve #11 `slice index starts at 1025 but ends at 1024`.
This bug made pkdns panic in case the UDP datagram was exactly 1024 bytes.
> fix: anydns bump + pkdns v0.5.2

- README.md
Fixes the problem that browsers on Windows can't handle `http://7fmjpcuuzf54hw18bsgi3zihzyh4awseeuq5tmojefaezjbd64cy/` but instead require the root dot `http://7fmjpcuuzf54hw18bsgi3zihzyh4awseeuq5tmojefaezjbd64cy./` at the end.
#12 #13.
> fix: change demo url for browser compatibility

- Cargo.lock
- README.md
- server/Cargo.toml
- server/pkdns.service
- server/src/helpers.rs
- server/src/main.rs
- server/src/packet_lookup.rs
- server/src/pkarr_resolver.rs
This PR improves pkdns logging by adding the `tracing` package.
For most users, nothing changes. The `--verbose` flag makes the output more chatty.
For advanced users, it adds the ability to set the environment variable `RUST_LOG=` to exactly guide pkdns what to log.
This is either done by setting the log level directly (`RUST_LOG=debug`) or by setting the log level for specific modules.
Examples:
- `RUST_LOG=pkdns=trace` will make pkdns very chatty.
- `RUST_LOG=any_dns=trace` will show everything related to ICANN forwarding.
- `RUST_LOG=mainline=debug` will display mainline DHT logs.
These can also be combined: `RUST_LOG=pkdns=trace,any_dns=trace`.
Related #14
> feat: Improved logging

- .vscode/launch.json
- README.md
- docs/logging.md
- server/src/helpers.rs
RUST_LOG env variable didnt get respected with #26. This PR fixes this.
It also adds a doc for advanced logging.
> fix: respect RUST_LOG in env + advanced logging doc

- Cargo.lock
- README.md
- cli/sample/README.md
- server/Cargo.toml
- server/src/bootstrap_nodes.rs
- server/src/main.rs
- server/src/pkarr_cache.rs
- server/src/pkarr_resolver.rs
So far, pkarr packets got cached for 60s and then discarded. This PR changes the following:
- Adds a LRU cache. Packets never get evicted as long there is space in the cache.
- Respects the packet TTL. The packet TTL is the lowest ttl of any entry.
- Added `--min-ttl` (default 5min), `--max-ttl` (default 24hrs), and `--cache-mb` (default 100MB) options to control cache behaviour. 
**Resilience** TTLs don't lead to cache eviction but is a sign that the server needs to refresh the cache. In case the packet is not found on the DHT anymore, the cached value is still kept alive. In case the fetched DHT value is older than the cached value, the newer cached value is kept.
**Deprecations** `--cache-ttl` and `--threads <threads>` were removed.
Solves #19
> feat: Improved TTL Caching

- .vscode/launch.json
- cli/src/commands/resolve.rs
- cli/src/helpers.rs
- cli/src/main.rs
- cli/src/pkarr_publisher.rs
- server/src/pkarr_resolver.rs
Removes resolver from PKDNS because they lead to bad performance when updating values on the DHT. Might re-add later but the current state is unbearable.
> fix: bad dht resolution when updating values

- server/src/main.rs
Reduces min ttl from 300s (5min) to 60s so devs can debug their apps better.
> chore: reduce min-ttl to 60s

- cli/src/cli.rs
- cli/src/commands/mod.rs
- cli/src/commands/publickey.rs
Adds an easy CLI command so one can easily derive a public key from a seed.
```
pkdns-cli publickey seed.txt
> eqa3q4o3dixqow5e6k75ifx5dwkahjyg7rx3j8eoh1s1fescys6o
```
> feat: publickey cli command

- server/src/pkarr_resolver.rs
Dashmap https://github.com/xacrimon/dashmap/issues/316 occasionally causes a deadlock on Ubuntu 24. This froze the whole server. Mac would work just fine.
This PR replaces DashMap with a regular Mutex<HashMap>. Slower but works.
> fix: Deadlocks freezing the whole server after two DHT calls

- Cargo.lock
- cli/Cargo.toml
- cli/sample/pkarr.zone
- cli/src/commands/publish.rs
- cli/src/external_ip/mod.rs
- cli/src/external_ip/providers/external_ip_resolver.rs
- cli/src/external_ip/providers/icanhazip.rs
- cli/src/external_ip/providers/identme.rs
- cli/src/external_ip/providers/ipifyorg.rs
- cli/src/external_ip/providers/ipinfoio.rs
- cli/src/external_ip/providers/mod.rs
- cli/src/external_ip/providers/myip.rs
- cli/src/external_ip/resolver.rs
- cli/src/main.rs
- docs/dns-over-https.md
- docs/dyn-dns.md
Adds support for two variables `{external_ipv4}` and `{external_ipv6}` to the pkarr.zone file. The two variables enable to use a PKD as DynDNS.
Background:
pkdns-cli uses the following services to determine the devices external IP address:
- icanhazip
- identme
- ipifyorg
- ipinfoio
- myip
If `{external_ipv4}` or `{external_ipv6}` is found in the pkarr.zone file, pkdns-cli will replace it with the resolved IP. In combination with the 60min crontab task to republish the zone, this acts as a DynDNS.
This partially resolves #25. Assuming a 60min republishing crontab task and a 5min TTL, a IP change will propagate within 65min. This is not perfect but a start. In the future, we should be able to optimize this down to 6min buyt this will require additional work.
> feat: {external_ipv4} and {external_ipv6} variables (DynDNS)

- Cargo.lock
- Cargo.toml
- server/Cargo.toml
- server/pkdns.service
- server/sample-config.toml
- server/src/config/config_file.rs
- server/src/config/mod.rs
- server/src/helpers.rs
- server/src/main.rs
- server/src/resolution/dns_socket.rs
- server/src/resolution/dns_socket_builder.rs
- server/src/resolution/pkd/pkarr_resolver.rs
- server/src/resolution/rate_limiter.rs
- Adds support for a toml config file called `pkdns.toml`.
- Uses the same pattern as in lnd or cln. Uses the `~/.pkdns` folder by default to save data and its config file.
- The `.pkdns` folder will be used for saving the cache to disk in the future.
- Reduce the number of cmd line args to a minimum to minimize the config effort. Might add more again later. This is a BREAKING CHANGE.
- Refactored cli args in general.
- Added sample config file.
> feat: toml config file

- Cargo.lock
- server/Cargo.toml
- server/sample-config.toml
- server/src/config/config_file.rs
- server/src/config/global.rs
- server/src/config/mod.rs
- server/src/main.rs
- server/src/resolution/dns_socket.rs
Adds a config to disable `ANY` type queries. This is to prevent DNS Amplification attacks.
By default `disable_any_queries` is false.
Also, refactored the configuration. It is now available globally. This improves the readability of the code.
> feat: Add option to disable ANY type queries

- server/sample-config.toml
- server/src/config/config_file.rs
- server/src/main.rs
- server/src/resolution/dns_socket.rs
- server/src/resolution/dns_socket_builder.rs
- server/src/resolution/helpers.rs
- server/src/resolution/mod.rs
- server/src/resolution/response_cache.rs
Add support for the caching of ICANN responses.
New config variable: `icann_cache_mb`. Default: 100.
This should reduce the load on the forward server drastically.
Like with the pkarr cache, the icann cache can be controlled/disabled with the `min_ttl` and `max_ttl` settings.
> feat: ICANN response cache

- server/sample-config.toml
- server/src/config/config_file.rs
- server/src/config/global.rs
- server/src/config/mod.rs
- server/src/dns_over_https/server.rs
- server/src/helpers.rs
- server/src/main.rs
- server/src/resolution/dns_socket.rs
- server/src/resolution/dns_socket_builder.rs
- server/src/resolution/mod.rs
- server/src/resolution/pkd/mod.rs
- server/src/resolution/pkd/pkarr_cache.rs
- server/src/resolution/pkd/pkarr_resolver.rs
- server/src/resolution/pkd/top_level_domain.rs
- server/src/resolution/response_cache.rs
Adds optional support for a top level domain (TLD) on Public Key Domains. Raw public keys keep being supported.
By default, `.pkd` is the default tld. The public key `7fmjpcuuzf54hw18bsgi3zihzyh4awseeuq5tmojefaezjbd64cy` can be resolved directly or with the tld like `7fmjpcuuzf54hw18bsgi3zihzyh4awseeuq5tmojefaezjbd64cy.pkd`.
The tld is configurable in the settings and can be changed.
Resolves #37
> feat: Optional Top Level Domain for Public Key Domains

- Dockerfile
Fixes the docker build. arm64 would only work on arm cpu. Switched to amd64 as it is the most widely used plattform.
Resolves #84
> fix(docker): Use amd64 instead of arm64

- cli/src/cli.rs
Configures clap to show the CLI usage if no arguments are provided.
I'm not particularly familiar with Clap or Rust, but this confused me when I was using the CLI, so figured I'd have a crack at fixing it!
It looks as though the subcommands might benefit from the same config; are there any you're expecting to operate without args? (`publish` looks like maybe?)
> CLI: Show usage when no args

- cli/src/cli.rs
- cli/src/commands/publish.rs
Execute help if publish is called without args + cleaned up two unnecessary sections.
Related to #92.
> fix(cli): show help if `publish` subcommand without args

- Cargo.lock
- cli/Cargo.toml
- cli/src/cli.rs
- cli/src/commands/generate.rs
- cli/src/commands/publish.rs
Previously, the seed was saved in zbase32. This is not compliant with https://github.com/pubky/pkarr/pull/166.
This PR changes the seed to HEX. zbase32 seeds are still supported for backwards compatibility.
> feat(cli): change the seed to hex format

- server/src/resolution/dns_socket.rs
Fixes
```
Aug 15 01:56:11 pkdns.europe-west6-b.c.pubky-prod.internal pkdns[3398084]: 2025-08-15T01:56:11.689194Z ERROR pkdns: Thread paniced. Stop main thread too.
Aug 15 01:56:11 pkdns.europe-west6-b.c.pubky-prod.internal pkdns[3398084]: thread 'tokio-runtime-worker' panicked at server/src/resolution/dns_socket.rs:161:42:
Aug 15 01:56:11 pkdns.europe-west6-b.c.pubky-prod.internal pkdns[3398084]: called `Result::unwrap()` on an `Err` value: [20, 139, 129, 128, 0, 1, 0, 0, 0, 1, 0, 1, 5, 114, 101, 108, 97, 121, 4, 104, 111, 100, 108, 2, 97, 114, 0, 0, 65, 0, 1, 192, 18, 0, 6, 0, 1, 0, 0, 2, 88, 0, 62, 3, 110, 115, 49, 10, 118, 101, 114, 99, 101, 108, 45, 100, 110, 115, 3, 99, 111, 109, 0, 10, 104, 111, 115, 116, 109, 97, 115, 116, 101, 114, 5, 110, 115, 111, 110, 101, 3, 110, 101, 116, 0, …
```
> fix(hs): Panic when forward server answers late
